[package]
name = "fortifier-macros-tests"
description = "Tests for Fortifier macros. Separate package to prevent a cycle."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true

# TODO: Remove after adding more tests.
[package.metadata.cargo-machete]
ignored = ["chrono", "rust_decimal", "uuid"]

[dependencies]

[dev-dependencies]
chrono.workspace = true
constant-string.workspace = true
email_address.workspace = true
fortifier = { workspace = true, features = [
    "all-types",
    "all-validations",
    "serde",
] }
indexmap.workspace = true
phonenumber.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
trybuild = "1.0.114"
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
