[book]
authors = ["DaniÃ«lle Huisman"]
language = "en"
src = "src"
title = "Fortifier"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css", "theme/theme.css"]
additional-js = ["theme/tabs.js"]
edit-url-template = "https://github.com/RustForWeb/fortifier/edit/main/book/{path}"
git-repository-url = "https://github.com/RustForWeb/fortifier"

[rust]
edition = "2024"
